# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# 
model: vgg16
load_checkpoint_path: ./checkpoints/vgg16/01_None
#load_checkpoint_path:
checkpoint_folder: ./checkpoints/vgg16/
batch_size: 128
epochs: 100

# LR Schedule
load_schedule: False
scheduler_step: 4
gamma: 0.8

# 
train_folder: ../data/carvana/masked_images_small
test_folder:  ../data/carvana/masked_images_small
validation_folder:  ../data/carvana/masked_images_small
label_path: ../data/carvana/metadata.csv

early_stopping: False
train: False
test: True
validate_every_X_epochs: 2

# data options
class_weighting: False
input_dim_a: 3                              # number of image channels [1/3]
input_dim_b: 3                              # number of image channels [1/3]
num_workers: 8                              # number of data loading threads
new_size: 256                               # first resize the shortest image side to this size
crop_image_height: 256                      # random crop image of this height
crop_image_width: 256                       # random crop image of this width
#data_root: ./datasets/edges2handbags/     # dataset folder location
